Repository discord-csharp/MODiX, pull requests merged in 2018-11, with the labels that each got.

#230 Remove BotHooks
  Modix.Bot/ModixBot.cs
  Modix.Bot/ModixBotHooks.cs
  Modix.Services/Adapters/DiscordAdapter.cs
  Modix.Services/AutoCodePaste/CodePasteHandler.cs
  Modix.Services/AutoCodePaste/CodePasteSetup.cs
  Modix.Services/CommandHelp/CommandErrorHandler.cs
  Modix.Services/CommandHelp/CommandHelpSetup.cs
  Modix.Services/GuildInfo/GuildInfoService.cs
  Modix.Services/GuildInfo/GuildInfoSetup.cs
  Modix.Services/Messages/Discord/ReactionAdded.cs
  Modix.Services/Messages/Discord/ReactionRemoved.cs
  Modix.Services/Messages/Discord/UserJoined.cs
  Modix.Services/Messages/Discord/UserLeft.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: refactoring

#233 Refactor promotion logging to use Mediatr
  Modix.Bot/Behaviors/PromotionLoggingHandler.cs
  Modix.Data/Messages/PromotionActionCreated.cs
  Modix.Data/Modix.Data.csproj
  Modix.Data/Repositories/IPromotionActionEventHandler.cs
  Modix.Data/Repositories/PromotionActionEventRepositoryBase.cs
  Modix.Data/Repositories/PromotionCampaignRepository.cs
  Modix.Data/Repositories/PromotionCommentRepository.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: refactoring

#237 Add more logging, improve exception serialization
  Modix.Services/Adapters/DiscordAdapter.cs
  Modix.Services/Moderation/ModerationInvitePurgingHandler.cs
  Modix.Services/Utilities/ExceptionContractResolver.cs
  Modix/Program.cs
Labels: enhancement

#240 Possible fix for NRE when adding reactions
  Modix.Services/CommandHelp/CommandErrorHandler.cs
Labels: bug
