Repository discord-csharp/MODiX, pull requests merged in 2019-04, with the labels that each got.

#385 Add option to view the context of a mass deletion
  Modix.Data/Models/Moderation/DeletedMessageSummary.cs
  Modix/ClientApp/src/app/Util.ts
  Modix/ClientApp/src/components/Autocomplete.vue
  Modix/ClientApp/src/components/Logs/BatchDeleteContext.vue
  Modix/ClientApp/src/components/Logs/DeletedMessages.vue
  Modix/ClientApp/src/components/UserLookup/UserProfile.vue
  Modix/ClientApp/src/components/UserLookup/UserProfileField.vue
  Modix/ClientApp/src/components/UserLookup/UserProfileSectionTitle.vue
  Modix/ClientApp/src/components/UserLookup/UserSearch.vue
  Modix/ClientApp/src/models/EphemeralUser.ts
  Modix/ClientApp/src/models/logs/DeletedMessageAbstraction.ts
  Modix/ClientApp/src/services/LogService.ts
  Modix/ClientApp/src/styles/components/autocomplete.scss
  Modix/ClientApp/src/styles/components/batchDeleteContext.scss
  Modix/ClientApp/src/styles/components/miniProfile.scss
  Modix/ClientApp/src/styles/components/userProfile.scss
  Modix/ClientApp/src/styles/required.scss
  Modix/ClientApp/src/styles/variables.scss
  Modix/ClientApp/src/views/Configuration/ChannelDesignations.vue
  Modix/ClientApp/src/views/UserLookup.vue
  Modix/Controllers/LogController.cs
  Modix/Controllers/UserInformationController.cs
  Modix/Models/DeletedMessageAbstraction.cs
Labels: enhancement

#404 Fixes #274: Removed Abstained from Promotion Approval Percentage
  Modix.Data/Utilities/EntityExtensions.cs
Labels: bug

#402 Unify display of names to Username#Discrim
  Modix.Bot/Behaviors/ModerationLoggingBehavior.cs
  Modix.Bot/Modules/EmojiStatsModule.cs
  Modix.Bot/Modules/IlModule.cs
  Modix.Bot/Modules/InfractionModule.cs
  Modix.Bot/Modules/ModerationModule.cs
  Modix.Bot/Modules/MoveMessageModule.cs
  Modix.Bot/Modules/PromotionsModule.cs
  Modix.Bot/Modules/ReplModule.cs
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Data/Models/Core/GuildUserBrief.cs
  Modix.Data/Models/Moderation/DeletedMessageSearchCriteria.cs
  Modix.Data/Models/Moderation/InfractionSearchCriteria.cs
  Modix.Data/Models/Moderation/InfractionSummary.cs
  Modix.Services/CodePaste/CodePasteService.cs
  Modix.Services/Core/AuthorizationService.cs
  Modix.Services/Core/MessageLogBehavior.cs
  Modix.Services/Moderation/InfractionSyncingHandler.cs
  Modix.Services/PopularityContest/PopularityContestService.cs
  Modix.Services/Promotions/PromotionLoggingHandler.cs
  Modix.Services/Promotions/PromotionsService.cs
  Modix.Services/Quote/QuoteService.cs
  Modix.Services/Starboard/StarboardHandler.cs
  Modix.Services/Utilities/EmbedBuilderExtensions.cs
  Modix.Services/Utilities/GuildUserExtensions.cs
  Modix.Services/Utilities/UserExtensions.cs
  Modix/ClientApp/src/components/Logs/Infractions.vue
  Modix/ClientApp/src/components/Promotions/PromotionListItem.vue
  Modix/ClientApp/src/models/core/GuildUserIdentity.ts
  Modix/ClientApp/src/views/Promotions.vue
  Modix/ClientApp/src/views/Tags/Tags.vue
  Modix/Controllers/LogController.cs
  Modix/Models/DeletedMessageAbstraction.cs
  Modix/Models/ModixUser.cs
Labels: enhancement, refactoring

#408 Fix display names across frontend
  Modix/ClientApp/src/components/Logs/InfractionTable.vue
  Modix/ClientApp/src/components/Logs/Infractions.vue
  Modix/ClientApp/src/components/Promotions/PromotionListItem.vue
  Modix/ClientApp/src/models/core/GuildUserIdentity.ts
  Modix/ClientApp/src/views/Promotions.vue
  Modix/ClientApp/src/views/Tags/Tags.vue
Labels: bug, refactoring

#409 Refactor CommandErrorHandler
  Modix.Bot/ModixBot.cs
  Modix.Services/CommandHelp/CommandErrorHandler.cs
  Modix.Services/CommandHelp/CommandHelpSetup.cs
Labels: enhancement, refactoring

#412 More Abstraction fixes
  Discord.Net.Abstractions/Core/IEmote.cs
  Discord.Net.Abstractions/Core/IEmoteEntity.cs
  Discord.Net.Abstractions/Rest/IBaseDiscordClient.cs
  Discord.Net.Abstractions/Rest/IDiscordRestClient.cs
  Discord.Net.Abstractions/Rest/IIRestMessageChannel.cs
  Discord.Net.Abstractions/Rest/IIRestPrivateChannel.cs
  Discord.Net.Abstractions/Rest/IRestChannel.cs
  Discord.Net.Abstractions/Rest/IRestGuildChannel.cs
  Discord.Net.Abstractions/Rest/IRestInvite.cs
  Discord.Net.Abstractions/Rest/IRestMessage.cs
  Discord.Net.Abstractions/Rest/IRestUser.cs
  Discord.Net.Abstractions/Rest/IRestWebhookUser.cs
  Discord.Net.Abstractions/WebSocket/IBaseSocketClient.cs
  Discord.Net.Abstractions/WebSocket/IISocketMessageChannel.cs
  Discord.Net.Abstractions/WebSocket/IISocketPrivateChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketGuildChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketMessage.cs
  Discord.Net.Abstractions/WebSocket/ISocketReaction.cs
  Discord.Net.Abstractions/WebSocket/ISocketUnknownUser.cs
  Discord.Net.Abstractions/WebSocket/ISocketUser.cs
  Modix.Bot/Modules/EmojiStatsModule.cs
  Modix.Bot/Modules/IlModule.cs
  Modix.Services/Core/MessageLogBehavior.cs
  Modix.Services/EmojiStats/EmojiUsageHandler.cs
  Modix.Services/Moderation/AttachmentBlacklistBehavior.cs
  Modix.Services/Quote/MessageLinkBehavior.cs
Labels: refactoring

#413 You want test? Maybe I make you test. Maybe I make you more abstraction layer.
  Modix.Common.Test/Mocks/FakeAsyncEvent.cs
  Modix.Common/Messaging/MessagingSetup.cs
  Modix.Services.Test/Core/DiscordSocketListeningBehaviorTests.cs
  Modix.Services.Test/Core/Messages/MessageDeletedNotificationTests.cs
  Modix.Services.Test/Core/Messages/MessageReceivedNotificationTests.cs
  Modix.Services.Test/Core/Messages/MessageUpdatedNotificationTests.cs
  Modix.Services.Test/Core/Messages/ReactionAddedNotificationTests.cs
  Modix.Services.Test/Core/Messages/ReactionRemovedNotificationTests.cs
  Modix.Services.Test/Core/Messages/UserBannedNotificationTests.cs
  Modix.Services.Test/Core/Messages/UserJoinedNotificationTests.cs
  Modix.Services.Test/Core/Messages/UserLeftNotificationTests.cs
  Modix.Services/Core/CoreSetup.cs
  Modix.Services/Core/DiscordSocketListeningBehavior.cs
  Modix.Services/Core/Messages/MessageDeletedNotification.cs
  Modix.Services/Core/Messages/MessageReceivedNotification.cs
  Modix.Services/Core/Messages/MessageUpdatedNotification.cs
  Modix.Services/Core/Messages/ReactionAddedNotification.cs
  Modix.Services/Core/Messages/ReactionRemovedNotification.cs
  Modix.Services/Core/Messages/UserBannedNotification.cs
  Modix.Services/Core/Messages/UserJoinedNotification.cs
  Modix.Services/Core/Messages/UserLeftNotification.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: unit testing

#419 Abstraction fixes: null checks
  Discord.Net.Abstractions/Rest/IBaseDiscordClient.cs
  Discord.Net.Abstractions/Rest/IDiscordRestClient.cs
  Discord.Net.Abstractions/Rest/IRestChannel.cs
  Discord.Net.Abstractions/Rest/IRestDMChannel.cs
  Discord.Net.Abstractions/Rest/IRestGroupChannel.cs
  Discord.Net.Abstractions/Rest/IRestGuild.cs
  Discord.Net.Abstractions/Rest/IRestGuildChannel.cs
  Discord.Net.Abstractions/Rest/IRestTextChannel.cs
  Discord.Net.Abstractions/Rest/IRestWebhook.cs
  Discord.Net.Abstractions/Rest/IRestWebhookUser.cs
  Discord.Net.Abstractions/WebSocket/IBaseSocketClient.cs
  Discord.Net.Abstractions/WebSocket/IDiscordShardedClient.cs
  Discord.Net.Abstractions/WebSocket/ISocketChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketDMChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketGroupChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketGuild.cs
  Discord.Net.Abstractions/WebSocket/ISocketGuildChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketTextChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketWebhookUser.cs
Labels: bug, refactoring

#420 MessageDispatcher.Dispatch() Exception handling
  Modix.Common.Test/Messaging/MessageDispatcherTests.cs
  Modix.Common/Messaging/MessageDispatcher.cs
Labels: refactoring

#425 Removed unnecessary ternary in AuthorizationModule
  Modix.Bot/Modules/AuthorizationModule.cs
Labels: refactoring

#418 IReadySyncrhonizationProvider and ISelfUserProvider
  Modix.Services.Test/Core/DiscordSocketListeningBehaviorTests.cs
  Modix.Services.Test/Core/Messages/ReadyNotificationTests.cs
  Modix.Services.Test/Core/ReadySynchronizationProviderTests.cs
  Modix.Services.Test/Core/SelfUserProviderTests.cs
  Modix.Services.Test/Moderation/InvitePurgingBehaviorTests.cs
  Modix.Services/CommandHelp/CommandErrorHandler.cs
  Modix.Services/Core/CoreSetup.cs
  Modix.Services/Core/DiscordSocketListeningBehavior.cs
  Modix.Services/Core/Messages/ReadyNotification.cs
  Modix.Services/Core/ReadySynchronizationProvider.cs
  Modix.Services/Core/SelfUserProvider.cs
  Modix.Services/Moderation/InvitePurgingBehavior.cs
  Modix.Services/Moderation/MutePersistingHandler.cs
  Modix.Services/Promotions/PromotionLoggingHandler.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: refactoring

#421 Refactored Claims Module
  Modix.Bot/Modules/AuthorizationModule.cs
  Modix/ClientApp/package-lock.json
Labels: refactoring

#423 Pingrole permission bugfix
  Modix.Bot/Modules/MarkerRoleModule.cs
Labels: bug

#427 Updates to build and test procedures for deployment...
  Modix.Common.Test/Modix.Common.Test.csproj
  Modix.Services.Test/Modix.Services.Test.csproj
  Modix.sln
  build/build.sh
  build/test.sh
Labels: deployment

#430 Added pingrole list command
  Modix.Bot/Modules/MarkerRoleModule.cs
Labels: enhancement

#433 Fix error when retrieving designated channels/roles
  Modix/Controllers/ChannelController.cs
  Modix/Controllers/RoleController.cs
Labels: bug

#436 ChannelTrackingBehavior Refactoring/Testing
  Modix.Data.Test/Repositories/GuildChannelRepositoryTests.cs
  Modix.Data/Repositories/GuildChannelRepository.cs
  Modix.Services.Test/Core/ChannelServiceTests.cs
  Modix.Services.Test/Core/ChannelTrackingBehaviorTests.cs
  Modix.Services.Test/Core/DiscordSocketListeningBehaviorTests.cs
  Modix.Services.Test/Core/Messages/ChannelCreatedNotificationTests.cs
  Modix.Services.Test/Core/Messages/ChannelUpdatedNotificationTests.cs
  Modix.Services/Core/ChannelService.cs
  Modix.Services/Core/ChannelTrackingBehavior.cs
  Modix.Services/Core/CoreSetup.cs
  Modix.Services/Core/DiscordSocketListeningBehavior.cs
  Modix.Services/Core/Messages/ChannelCreatedNotification.cs
  Modix.Services/Core/Messages/ChannelUpdatedNotification.cs
Labels: refactoring, unit testing

#450 Remove hardcoded enums in the documentation service
  Modix.Services/Csharp/DocumentationApiResponse.cs
Labels: bug

#441 Fix exception when searching claims for an ID that doesn't refer to an actual user in the guild
  Modix.Bot/Modules/AuthorizationModule.cs
Labels: bug

#444 Add confirmations to commands where it makes sense, minor cleanup
  Modix.Bot/Modules/AuthorizationModule.cs
  Modix.Bot/Modules/DesignatedChannelModule.cs
  Modix.Bot/Modules/DesignatedRoleModule.cs
  Modix.Bot/Modules/PromotionsModule.cs
Labels: enhancement, refactoring

#453 Fixed #452 by Removing Timestamp from Infractions Module
  Modix.Bot/Modules/InfractionModule.cs
Labels: refactoring

#457 Fix NRE in ICacheable abstraction
  Discord.Net.Abstractions/Core/ICacheable.cs
  Modix.Services/EmojiStats/EmojiUsageHandler.cs
Labels: bug

#455 Cache dominant colors from avatars
  Modix.Bot/Modules/GuildInfoModule.cs
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Services/Images/ColorQuantization/Octree.cs
  Modix.Services/Images/ColorQuantization/OctreeNode.cs
  Modix.Services/Images/ColorQuantization/PaletteItem.cs
  Modix.Services/Images/ImageService.cs
  Modix.Services/Images/SetupImages.cs
  Modix.Services/Utilities/FormatUtilities.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: refactoring

#440 Always refresh promotion comments after adding or editing a comment
  Modix/ClientApp/src/components/Promotions/PromotionCommentEditModal.vue
  Modix/ClientApp/src/components/Promotions/PromotionCommentView.vue
  Modix/ClientApp/src/components/Promotions/PromotionListItem.vue
  Modix/ClientApp/src/views/Promotions.vue
Labels: bug

#458 Add database check to `QuoteModule`
  Modix.Bot/Modules/QuoteModule.cs
Labels: refactoring

#464 Giveaways Fix & Enhancement
  Modix.Bot/AnyGuildMessage.cs
  Modix.Bot/AnyGuildMessageTypeReader.cs
  Modix.Bot/MessageTypeReader.cs
  Modix.Bot/Modules/GiveawayModule.cs
  Modix.Services/Core/MessageService.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: bug, enhancement

#466 Properly use forwarded reverse proxy headers
  Modix/Startup.cs
Labels: bug
