Repository discord-csharp/MODiX, pull requests merged in 2019-10, with the labels that each got.

#596 Run handlers simultaneously
  Modix.Common/Messaging/MessageDispatcher.cs
  Modix.Common/Messaging/MessagePublisher.cs
Labels: refactoring

#598 Reverting the prior (parallelism) commit, because it broke MODiX...
  Modix.Common/Messaging/MessageDispatcher.cs
  Modix.Common/Messaging/MessagePublisher.cs
Labels: bug

#597 Added ability to remove Docs embed
  Modix.Bot/Modules/DocumentationModule.cs
Labels: enhancement

#614 Fix NRE triggered by starring a message that is a quote
  Modix.Services/Starboard/StarboardHandler.cs
Labels: bug
