Repository discord-csharp/MODiX, pull requests merged in 2019-05, with the labels that each got.

#477 Various frontend & tooling updates
  Modix/ClientApp/dev-server-running.js
  Modix/ClientApp/package-lock.json
  Modix/ClientApp/package.json
  Modix/ClientApp/src/app/Util.ts
  Modix/ClientApp/src/app/discord-markdown/LICENSE
  Modix/ClientApp/src/app/discord-markdown/index.js
  Modix/ClientApp/src/components/Logs/InfractionTable.vue
  Modix/ClientApp/src/components/Logs/Infractions.vue
  Modix/ClientApp/src/models/infractions/InfractionType.ts
  Modix/ClientApp/src/shims.d.ts
  Modix/ClientApp/vue.config.js
  Modix/Modix.csproj
  Modix/Properties/launchSettings.json
Labels: deployment, enhancement, refactoring

#476 Move website base url out to bot config.
  Modix.Bot/Behaviors/ModerationLoggingBehavior.cs
  Modix.Bot/Extensions/UriBuilderExtensions.cs
  Modix.Bot/ModixBot.cs
  Modix.Bot/Modules/DesignatedChannelModule.cs
  Modix.Bot/Modules/DesignatedRoleModule.cs
  Modix.Bot/Modules/HelpModule.cs
  Modix.Bot/Modules/InfractionModule.cs
  Modix.Bot/Modules/PromotionsModule.cs
  Modix.Bot/Modules/TagModule.cs
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Data/Models/Core/ModixConfig.cs
  Modix/developmentSettings.default.json
Labels: enhancement

#478 Add new TimeSpanTypeReader, allowing for formats such as "24h"
  Modix.Bot.Test/.editorconfig
  Modix.Bot.Test/AssemblyInfo.cs
  Modix.Bot.Test/Modix.Bot.Test.csproj
  Modix.Bot.Test/TimeSpanTypeReaderTests.cs
  Modix.Bot/AssemblyInfo.cs
  Modix.Bot/TimeSpanTypeReader.cs
  Modix.sln
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: enhancement

#481 Improvements to Ping module
  Modix.Bot/Modules/PingModule.cs
Labels: enhancement

#484 Change latency sentinel value to -1
  Modix.Bot/Modules/PingModule.cs
Labels: bug

#486 Fix NRE thrown by the campaign list command
  Modix.Bot/Modules/PromotionsModule.cs
Labels: bug

#489 Sanitize output of !help
  Modix.Bot/Modules/HelpModule.cs
Labels: bug

#492 Fix next rank determination logic in promotions
  Modix.Services/Promotions/PromotionsService.cs
Labels: bug

#491 Improvements to usefulness of Ping module
  Modix.Bot/Modules/PingModule.cs
Labels: enhancement

#493 Fix user-agent
  Modix.Bot/Modules/PingModule.cs
Labels: bug
