Repository discord-csharp/MODiX, pull requests merged in 2019-02, with the labels that each got.

#263 Improvements to Promotions
  Modix.Bot/Behaviors/PromotionLoggingHandler.cs
  Modix.Bot/Modules/DesignatedChannelModule.cs
  Modix.Bot/Modules/PromotionsModule.cs
  Modix.Data/Models/Core/DesignatedChannelType.cs
  Modix.Data/Models/Promotions/PromotionCampaignSearchCriteria.cs
  Modix.Data/Utilities/EntityExtensions.cs
  Modix.Services/Promotions/PromotionsService.cs
  Modix/ClientApp/src/components/Configuration/IndividualDesignation.vue
  Modix/ClientApp/src/components/MiniProfile.vue
  Modix/ClientApp/src/components/Promotions/PromotionCommentEditModal.vue
  Modix/ClientApp/src/components/Promotions/PromotionCommentView.vue
  Modix/ClientApp/src/components/Promotions/PromotionListItem.vue
  Modix/ClientApp/src/models/moderation/ChannelDesignation.ts
  Modix/ClientApp/src/services/PromotionService.ts
  Modix/ClientApp/src/styles/components/configuration.scss
  Modix/ClientApp/src/styles/components/miniProfile.scss
  Modix/ClientApp/src/styles/components/promotionCommentView.scss
  Modix/ClientApp/src/styles/components/promotionListItem.scss
  Modix/ClientApp/src/styles/mixins/modal-dark-bg.scss
  Modix/ClientApp/src/styles/required.scss
  Modix/ClientApp/src/styles/themes/holiday.scss
  Modix/ClientApp/src/styles/themes/spoopy.scss
  Modix/ClientApp/src/styles/variables.scss
  Modix/ClientApp/src/views/CreatePromotion.vue
  Modix/ClientApp/src/views/Infractions.vue
  Modix/ClientApp/src/views/Promotions.vue
  Modix/Controllers/ModixController.cs
  Modix/Controllers/PromotionController.cs
Labels: enhancement

#312 Reduce logging from ModerationInvitePurgingHandler
  Modix.Services/Moderation/ModerationInvitePurgingHandler.cs
Labels: enhancement

#308 UserInfo embed should include how a user's activity compares to others
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Data/Models/Core/GuildUserParticipationStatistics.cs
  Modix.Data/ModixContext.cs
  Modix.Data/Repositories/MessageRepository.cs
Labels: enhancement

#311 Add starboard functionality
  Modix.Services/Starboard/StarboardHandler.cs
  Modix.Services/Starboard/StarboardService.cs
  Modix/ClientApp/src/models/moderation/ChannelDesignation.ts
Labels: enhancement, proposal

#313 Use HttpClientFactory in place of HttpClient
  Modix.Bot/Modix.Bot.csproj
  Modix.Bot/Modules/DocumentationModule.cs
  Modix.Bot/Modules/FunModule.cs
  Modix.Bot/Modules/IlModule.cs
  Modix.Bot/Modules/ReplModule.cs
  Modix.Bot/Modules/StackExchangeModule.cs
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Bot/Modules/WikipediaModule.cs
  Modix.Services/AutoCodePaste/CodePasteService.cs
  Modix.Services/Csharp/DocumentationService.cs
  Modix.Services/DocsMaster/DocsMasterRetrievalService.cs
  Modix.Services/Modix.Services.csproj
  Modix.Services/StackExchange/StackExchangeService.cs
  Modix.Services/Utilities/DiscordWebhookSink.cs
  Modix.Services/Wikipedia/WikipediaService.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
  Modix/Program.cs
  Modix/Startup.cs
Labels: refactoring
