Repository discord-csharp/MODiX, pull requests merged in 2020-02, with the labels that each got.

#703 Check the AddReactions permission before attempting to add reactions
  Modix.Bot/Extensions/CommandContextExtensions.cs
Labels: bug

#717 IEntityTypeConfiguration<TEntity> Usage
  Modix.Data/Models/BehaviourConfiguration.cs
  Modix.Data/Models/Core/ClaimMappingEntity.cs
  Modix.Data/Models/Core/ConfigurationActionEntity.cs
  Modix.Data/Models/Core/DesignatedChannelMappingEntity.cs
  Modix.Data/Models/Core/DesignatedRoleMappingEntity.cs
  Modix.Data/Models/Core/GuildChannelEntity.cs
  Modix.Data/Models/Core/GuildRoleEntity.cs
  Modix.Data/Models/Core/GuildUserEntity.cs
  Modix.Data/Models/Core/MessageEntity.cs
  Modix.Data/Models/Core/UserEntity.cs
  Modix.Data/Models/Emoji/EmojiEntity.cs
  Modix.Data/Models/Moderation/DeletedMessageBatchEntity.cs
  Modix.Data/Models/Moderation/DeletedMessageEntity.cs
  Modix.Data/Models/Moderation/InfractionEntity.cs
  Modix.Data/Models/Moderation/ModerationActionEntity.cs
  Modix.Data/Models/Promotions/PromotionActionEntity.cs
  Modix.Data/Models/Promotions/PromotionCampaignEntity.cs
  Modix.Data/Models/Promotions/PromotionCommentEntity.cs
  Modix.Data/Models/Tags/TagActionEntity.cs
  Modix.Data/Models/Tags/TagEntity.cs
  Modix.Data/ModixContext.cs
  Modix.Data/Utilities/OnModelCreatingAttribute.cs
Labels: refactoring

#719 MessageEntity.Id Snapshot Corruption
  Modix.Data/Migrations/ModixContextModelSnapshot.cs
  Modix.Data/Models/Core/MessageEntity.cs
Labels: bug

#723 EF ModelSnapshot Validation
  Modix.Data.Test/ModixContextTests.cs
Labels: unit testing

#722 DbSet<TEntity> Usage
  Modix.Data.Test/Repositories/ClaimMappingRepositoryTests.cs
  Modix.Data.Test/Repositories/ConfigurationActionRepositoryTests.cs
  Modix.Data.Test/Repositories/DesignatedChannelMappingRepositoryTests.cs
  Modix.Data.Test/Repositories/DesignatedRoleMappingRepositoryTests.cs
  Modix.Data.Test/Repositories/GuildChannelRepositoryTests.cs
  Modix.Data.Test/Repositories/GuildRoleRepositoryTests.cs
  Modix.Data.Test/Repositories/GuildUserRepositoryTests.cs
  Modix.Data.Test/TestDataContextFactory.cs
  Modix.Data/Models/BehaviourConfiguration.cs
  Modix.Data/Models/Core/ClaimMappingEntity.cs
  Modix.Data/Models/Core/ConfigurationActionEntity.cs
  Modix.Data/Models/Core/DesignatedChannelMappingEntity.cs
  Modix.Data/Models/Core/DesignatedRoleMappingEntity.cs
  Modix.Data/Models/Core/GuildChannelEntity.cs
  Modix.Data/Models/Core/GuildRoleEntity.cs
  Modix.Data/Models/Core/GuildUserEntity.cs
  Modix.Data/Models/Core/MessageEntity.cs
  Modix.Data/Models/Core/UserEntity.cs
  Modix.Data/Models/Moderation/DeletedMessageEntity.cs
  Modix.Data/Models/Moderation/InfractionEntity.cs
  Modix.Data/Models/Moderation/ModerationActionEntity.cs
  Modix.Data/Models/Promotions/PromotionActionEntity.cs
  Modix.Data/Models/Promotions/PromotionCampaignEntity.cs
  Modix.Data/Models/Promotions/PromotionCommentEntity.cs
  Modix.Data/ModixContext.cs
  Modix.Data/Repositories/BehaviourConfigurationRepository.cs
  Modix.Data/Repositories/ClaimMappingRepository.cs
  Modix.Data/Repositories/ConfigurationActionRepository.cs
  Modix.Data/Repositories/DeletedMessageBatchRepository.cs
  Modix.Data/Repositories/DeletedMessageRepository.cs
  Modix.Data/Repositories/DesignatedChannelMappingRepository.cs
  Modix.Data/Repositories/DesignatedRoleMappingRepository.cs
  Modix.Data/Repositories/EmojiRepository.cs
  Modix.Data/Repositories/GuildChannelRepository.cs
  Modix.Data/Repositories/GuildRoleRepository.cs
  Modix.Data/Repositories/GuildUserRepository.cs
  Modix.Data/Repositories/InfractionRepository.cs
  Modix.Data/Repositories/MessageRepository.cs
  Modix.Data/Repositories/ModerationActionRepository.cs
  Modix.Data/Repositories/PromotionActionRepository.cs
  Modix.Data/Repositories/PromotionCampaignRepository.cs
  Modix.Data/Repositories/PromotionCommentRepository.cs
  Modix.Services.Test/Tags/CreateTagTests.cs
  Modix.Services/Tags/TagService.cs
  Modix.Services/UserInfo/UserInfoCommand.cs
Labels: refactoring
