Repository discord-csharp/MODiX, pull requests merged in 2020-03, with the labels that each got.

#739 Made channel and role designations pull from backend
  Modix/ClientApp/src/app/Store.ts
  Modix/ClientApp/src/components/Configuration/IndividualDesignation.vue
  Modix/ClientApp/src/models/ModixState.ts
  Modix/ClientApp/src/models/moderation/ChannelDesignation.ts
  Modix/ClientApp/src/models/moderation/DesignatedChannelCreationData.ts
  Modix/ClientApp/src/models/moderation/DesignatedChannelMapping.ts
  Modix/ClientApp/src/models/moderation/DesignatedRoleCreationData.ts
  Modix/ClientApp/src/models/moderation/DesignatedRoleMapping.ts
  Modix/ClientApp/src/models/moderation/RoleDesignation.ts
  Modix/ClientApp/src/services/ConfigurationService.ts
  Modix/ClientApp/src/styles/components/designations.scss
  Modix/ClientApp/src/styles/required.scss
  Modix/ClientApp/src/views/Configuration/ChannelDesignations.vue
  Modix/ClientApp/src/views/Configuration/Claims.vue
  Modix/ClientApp/src/views/Configuration/Configuration.vue
  Modix/ClientApp/src/views/Configuration/RoleDesignations.vue
  Modix/Controllers/ChannelController.cs
  Modix/Controllers/RoleController.cs
Labels: enhancement

#740 Fix error when unbanning/unmuting
  Modix.Bot/Behaviors/ModerationLoggingBehavior.cs
Labels: bug

#731 Wiki V2: First Draft
  Modix.sln
  wiki/Application-Architecture.csv
  wiki/Application-Architecture.md
  wiki/Application-Architecture.svg
  wiki/Bot-Fontend.md
  wiki/Business-Logic.md
  wiki/Contributor's-Guidelines.md
  wiki/Data-Access-Modeling.md
  wiki/Data-Modeling.md
  wiki/Data-Storage.md
  wiki/Home.md
  wiki/Host-Process.md
  wiki/How-to-contribute.md
  wiki/Project-Overview.md
  wiki/Testing.md
  wiki/Web-API.md
  wiki/Web-Frontend.md
  wiki/_Footer.md
Labels: infrastructure

#736 Refactored `IBehavior` to resolve #732.
  Modix.Bot/ModixBot.cs
  Modix.Common.Test/AsyncMethodTestContext.cs
  Modix.Common.Test/AsyncMethodWithLoggerTestContext.cs
  Modix.Common.Test/Extensions/Microsoft/Extensions/Hosting/BehaviorHostTests.cs
  Modix.Common.Test/Extensions/Microsoft/Extensions/Hosting/ScopedStartupActionBaseTests.cs
  Modix.Common.Test/Extensions/System/Linq/EnumerableExtensions.cs
  Modix.Common.Test/Modix.Common.Test.csproj
  Modix.Common.Test/TestLoggerFactory.cs
  Modix.Common/Extensions/Microsoft/Extensions/DependencyInjection/ServiceScopeLogMessages.cs
  Modix.Common/Extensions/Microsoft/Extensions/Hosting/BehaviorHost.cs
  Modix.Common/Extensions/Microsoft/Extensions/Hosting/HostingLogMessages.cs
  Modix.Common/Extensions/Microsoft/Extensions/Hosting/IBehavior.cs
  Modix.Common/Extensions/Microsoft/Extensions/Hosting/ScopedStartupActionBase.cs
  Modix.Common/Extensions/Microsoft/Extensions/Logging/LoggerExtensions.cs
  Modix.Common/Modix.Common.csproj
  Modix.Data/Modix.Data.csproj
  Modix.Data/ModixContextAutoMigrationStartupAction.cs
  Modix.Data/ModixContextLogMessages.cs
  Modix.Services.Test/Core/DiscordSocketListeningBehaviorTests.cs
  Modix.Services/BehaviorBase.cs
  Modix.Services/Core/CoreSetup.cs
  Modix.Services/Core/DiscordSocketListeningBehavior.cs
  Modix.Services/IBehavior.cs
  Modix.Services/Moderation/ModerationSetup.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
  Modix/Startup.cs
Labels: bug, enhancement, proposal, refactoring
