Repository discord-csharp/MODiX, pull requests merged in 2020-09, with the labels that each got.

#821 Remove MediatR
  Directory.Build.targets
  Modix.Bot/Modix.Bot.csproj
  Modix.Bot/Modules/AnnounceModule.cs
  Modix.Bot/Modules/IsUpModule.cs
  Modix.Bot/Modules/MentionModule.cs
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Services/IsUp/IsUpCommand.cs
  Modix.Services/Mentions/MentionCommand.cs
  Modix.Services/Mentions/MentionService.cs
  Modix.Services/Modix.Services.csproj
  Modix.Services/UserInfo/UserInfoCommand.cs
  Modix/Modix.csproj
  Modix/Startup.cs
Labels: refactoring

#829 Add infraction creator to infractions embed
  Modix.Bot/Modules/InfractionModule.cs
Labels: enhancement

#831 Remove status from !info and online count from !guildinfo
  Modix.Bot/Modules/GuildInfoModule.cs
  Modix.Bot/Modules/UserInfoModule.cs
  Modix/ClientApp/src/components/UserLookup/UserProfile.vue
  Modix/ClientApp/src/models/EphemeralUser.ts
  Modix/Controllers/UserInformationController.cs
Labels: bug
