Repository discord-csharp/MODiX, pull requests merged in 2020-11, with the labels that each got.

#842 Add command to shorten links
  Modix.Bot/Modules/LinkModule.cs
  Modix.Bot/UriTypeReader.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: proposal

#833 Include infraction IDs in infraction creation logs
  Modix.Bot/Behaviors/ModerationLoggingBehavior.cs
Labels: enhancement

#849 Proposal to refactor ModerationService + Add logging for failing to apply perms to channels
  Modix.Services/Moderation/ModerationService.cs
Labels: refactoring
