Repository discord-csharp/MODiX, pull requests merged in 2020-05, with the labels that each got.

#745 ServiceBinding and ServiceConfigurator
  Modix.Common.Test/Extensions/Microsoft/Extensions/DependencyInjection/ServiceBindingAttributeTests.cs
  Modix.Common.Test/Extensions/Microsoft/Extensions/DependencyInjection/ServiceCollectionBindingExtensionsTests.cs
  Modix.Common.Test/Extensions/Microsoft/Extensions/DependencyInjection/ServiceConfiguratorAttributeTests.cs
  Modix.Common.Test/Extensions/Shouldly/EnumerableAssertions.cs
  Modix.Common.Test/Extensions/Shouldly/MoqAssertions.cs
  Modix.Common/CommonSetup.cs
  Modix.Common/Extensions/Microsoft/Extensions/DependencyInjection/DependencyInjectionLogMessages.cs
  Modix.Common/Extensions/Microsoft/Extensions/DependencyInjection/ServiceBindingAttribute.cs
  Modix.Common/Extensions/Microsoft/Extensions/DependencyInjection/ServiceCollectionBindingExtensions.cs
  Modix.Common/Extensions/Microsoft/Extensions/DependencyInjection/ServiceConfigurator.cs
  Modix.Common/Extensions/Microsoft/Extensions/DependencyInjection/ServiceConfiguratorAttribute.cs
  Modix.Common/Extensions/Microsoft/Extensions/Hosting/BehaviorHost.cs
  Modix.Common/Extensions/Microsoft/Extensions/Hosting/ScopedStartupActionBase.cs
  Modix.Common/Messaging/MessageDispatcher.cs
  Modix.Common/Messaging/MessagePublisher.cs
  Modix.Common/Messaging/MessagingSetup.cs
  Modix/Extensions/ServiceCollectionExtensions.cs
  Modix/Startup.cs
Labels: enhancement, refactoring

#763 Fix NullReferenceException when updating tags
  Modix.Services/Tags/TagService.cs
Labels: bug

#764 Add missed Discord.Net.Abstractions interface references
  Modix/Controllers/AutocompleteController.cs
  Modix/Controllers/ChannelController.cs
  Modix/Controllers/LogController.cs
Labels: bug

#771 Create Aliases
  Modix.Bot/Modules/MarkerRoleModule.cs
Labels: enhancement

#770 Refactored RoleService and RoleTrackingBehavior.
  Modix.Common/ApplicationLogEventType.cs
  Modix.Services.Test/Core/DiscordSocketListeningBehaviorTests.cs
  Modix.Services.Test/Core/Messages/RoleCreatedNotificationTests.cs
  Modix.Services.Test/Core/Messages/RoleUpdatedNotificationTests.cs
  Modix.Services.Test/Core/RoleServiceTests.cs
  Modix.Services.Test/Core/RoleTrackingBehaviorTests.cs
  Modix.Services/Core/CoreSetup.cs
  Modix.Services/Core/DiscordSocketListeningBehavior.cs
  Modix.Services/Core/Messages/RoleCreatedNotification.cs
  Modix.Services/Core/Messages/RoleUpdatedNotification.cs
  Modix.Services/Core/RoleService.cs
  Modix.Services/Core/RoleTrackingBehavior.cs
  Modix.Services/Core/RolesLogMessages.cs
  Modix.Services/Moderation/ModerationService.cs
  Modix.Services/ServicesLogEventType.cs
Labels: refactoring

#778 More robust message log embeds
  Modix.Services.Test/MessageLogging/MessageLoggingBehaviorTests.cs
  Modix.Services/MessageLogging/MessageLoggingBehavior.cs
Labels: bug
