Repository discord-csharp/MODiX, pull requests merged in 2020-01, with the labels that each got.

#641 Allow either the requesting or requested user to remove the info embed
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Services/AutoRemoveMessage/AutoRemoveMessageHandler.cs
  Modix.Services/AutoRemoveMessage/AutoRemoveMessageService.cs
  Modix.Services/AutoRemoveMessage/RemovableMessage.cs
  Modix.Services/AutoRemoveMessage/RemovableMessageSentNotification.cs
Labels: enhancement

#645 Don't attempt to quote messages that MODiX does not have access to
  Modix.Services/Quote/MessageLinkBehavior.cs
Labels: bug

#654 Respect the Unmoderated designation when autoconfiguring channels
  Modix.Services/Moderation/ModerationService.cs
Labels: bug

#660 Proposal for removing Repositories, starting with Tag Repository
  Modix.Data.Test/Repositories/TagRepositoryTests.cs
  Modix.Data/Models/Emoji/EmojiEntity.cs
  Modix.Data/Models/Tags/TagActionEntity.cs
  Modix.Data/Models/Tags/TagEntity.cs
  Modix.Data/Models/Tags/TagSearchCriteria.cs
  Modix.Data/Models/Tags/TagSummary.cs
  Modix.Data/ModixContext.cs
  Modix.Data/Repositories/TagRepository.cs
  Modix.Services.Test/Modix.Services.Test.csproj
  Modix.Services.Test/Tags/CreateTagTests.cs
  Modix.Services/Tags/TagService.cs
  Modix.Services/Tags/TagSetup.cs
  Modix/Controllers/TagController.cs
Labels: refactoring

#671 Proposal to add MediatR, refactor mention module/service, start #670
  Directory.Build.targets
  Modix.Bot/Modix.Bot.csproj
  Modix.Bot/Modules/AnnounceModule.cs
  Modix.Bot/Modules/MentionModule.cs
  Modix.Services/Core/AuthorizationService.cs
  Modix.Services/Mentions/MentionCommandHandler.cs
  Modix.Services/Mentions/MentionService.cs
  Modix.Services/Mentions/MentionSetup.cs
  Modix.Services/Modix.Services.csproj
  Modix/Extensions/ServiceCollectionExtensions.cs
  Modix/Modix.csproj
  Modix/Startup.cs
Labels: enhancement, refactoring

#667 Add user secrets to data project fix #666
  Directory.Build.props
  Directory.Build.targets
  Modix.Data/Modix.Data.csproj
  Modix.Data/ModixContextDesignFactory.cs
  Modix/Modix.csproj
  Modix/Program.cs
Labels: infrastructure

#669 Proposal for #668, change to use IEntityTypeConfiguration<TEntity>
  Modix.Data/Models/Tags/TagEntity.cs
  Modix.Data/ModixContext.cs
Labels: refactoring

#664 Fix queries improperly evaluated on client
  Modix.Data.Test/ExpandableQueries/ExpandableExtensionsTests.cs
  Modix.Data.Test/Repositories/InfractionRepositoryTests.cs
  Modix.Data/ExpandableQueries/ExpandableExtensions.cs
  Modix.Data/Models/Moderation/DeletedMessageSearchCriteria.cs
  Modix.Data/Models/Moderation/InfractionSearchCriteria.cs
  Modix.Data/Models/Tags/TagSearchCriteria.cs
  Modix.Data/Modix.Data.csproj
  Modix.Data/Repositories/InfractionRepository.cs
  Modix.Data/Utilities/Extensions.cs
  Modix.Data/Utilities/ReusableQueries.cs
Labels: bug

#694 Optimize user info queries
  Modix.Bot/Modules/UserInfoModule.cs
  Modix.Data/Models/Core/MessageCountByDate.cs
  Modix.Data/Models/Core/MessageCountPerChannel.cs
  Modix.Data/ModixContext.cs
  Modix.Data/Repositories/MessageRepository.cs
  Modix/Controllers/UserInformationController.cs
Labels: enhancement
