Repository discord-csharp/MODiX, pull requests merged in 2020-08, with the labels that each got.

#810 Upgrade node-sass to 4.14.1
  Modix/ClientApp/package-lock.json
  Modix/ClientApp/package.json
Labels: dependencies

#807 Fix NullReferenceException in !infraction update
  Modix.Bot/Modules/InfractionModule.cs
  Modix.Data/Repositories/InfractionRepository.cs
  Modix.Services/Moderation/ModerationService.cs
Labels: bug

#812 Fix NullReferenceException when adding a comment to a campaign
  Modix.Data/Repositories/PromotionCampaignRepository.cs
  Modix.Services/Core/AuthorizationService.cs
  Modix.Services/Promotions/PromotionsService.cs
Labels: bug

#814 Allow !infractions command to accept user names that contain spaces
  Modix.Bot/Modules/InfractionModule.cs
Labels: bug

#817 Revert "Remove guild members intent (#816)"
  Modix/Extensions/ServiceCollectionExtensions.cs
Labels: bug

#818 Update loadingMessages.json
  Modix/ClientApp/src/data/loadingMessages.json
Labels: bug

#813 Do not process code blocks and quotes in the TagInlineParsingHandler.
  Modix.Services/Tags/TagInlineParsingHandler.cs
Labels: enhancement
