Repository discord-csharp/MODiX, pull requests merged in 2021-06, with the labels that each got.

#879 upgrading to discord.net 2.4.0
  Directory.Build.targets
  Discord.Net.Abstractions/Rest/IBaseDiscordClient.cs
  Discord.Net.Abstractions/Rest/IDiscordRestClient.cs
  Discord.Net.Abstractions/Rest/IIRestMessageChannel.cs
  Discord.Net.Abstractions/Rest/IRestDMChannel.cs
  Discord.Net.Abstractions/Rest/IRestGroupChannel.cs
  Discord.Net.Abstractions/Rest/IRestGuild.cs
  Discord.Net.Abstractions/Rest/IRestGuildUser.cs
  Discord.Net.Abstractions/Rest/IRestInvite.cs
  Discord.Net.Abstractions/Rest/IRestInviteMetadata.cs
  Discord.Net.Abstractions/Rest/IRestMessage.cs
  Discord.Net.Abstractions/Rest/IRestRole.cs
  Discord.Net.Abstractions/Rest/IRestTextChannel.cs
  Discord.Net.Abstractions/Rest/IRestUser.cs
  Discord.Net.Abstractions/Rest/IRestUserMessage.cs
  Discord.Net.Abstractions/Rest/IRestWebhookUser.cs
  Discord.Net.Abstractions/WebSocket/IBaseSocketClient.cs
  Discord.Net.Abstractions/WebSocket/IISocketMessageChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketDMChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketGroupChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketGuild.cs
  Discord.Net.Abstractions/WebSocket/ISocketGuildUser.cs
  Discord.Net.Abstractions/WebSocket/ISocketMessage.cs
  Discord.Net.Abstractions/WebSocket/ISocketRole.cs
  Discord.Net.Abstractions/WebSocket/ISocketTextChannel.cs
  Discord.Net.Abstractions/WebSocket/ISocketUser.cs
  Discord.Net.Abstractions/WebSocket/ISocketUserMessage.cs
  Discord.Net.Abstractions/WebSocket/ISocketWebhookUser.cs
  Modix.Bot.Test/Modix.Bot.Test.csproj
  Modix.Common.Test/Extensions/Microsoft/Extensions/DependencyInjection/ServiceBindingAttributeTests.cs
  Modix.Common.Test/TestLoggerFactory.cs
  Modix.Data/Models/Core/EphemeralUser.cs
  Modix.Services.Test/Core/DiscordSocketListeningBehaviorTests.cs
  Modix.Services.Test/MessageLogging/MessageLoggingBehaviorTests.cs
  Modix.Services.Test/Moderation/AttachmentBlacklistBehaviorTests.cs
  Modix.Services.Test/Moderation/MessageContentCheckBehaviourTests.cs
Labels: dependencies

#853 !link command: fix description length error, avoid displaying <help.run.csharp> token
  Modix.Bot/Modix.Bot.csproj
  Modix.Bot/Modules/LinkModule.cs
Labels: bug

#882 Improve performance during infraction creation
  Modix.Services/Core/UserService.cs
  Modix.Services/Moderation/ModerationService.cs
Labels: refactoring
